import { createTheme } from '@uiw/codemirror-themes';
import { tags as t } from '@lezer/highlight';
import type { Extension } from '@codemirror/state';
import * as uiwThemes from '@uiw/codemirror-themes-all';
import { oneDark } from '@codemirror/theme-one-dark';

// 自定义主题：Catppuccin Mocha（无 @uiw 官方包）
const catppuccinMocha = createTheme({
  theme: 'dark',
  settings: {
    background: '#1E1E2E',
    foreground: '#CDD6F4',
    caret: '#F5E0DC',
    selection: '#585B7066',
    selectionMatch: '#585B7066',
    gutterBackground: '#1E1E2E',
    gutterForeground: '#6C7086',
    lineHighlight: '#FFFFFF08',
  },
  styles: [
    { tag: t.keyword, color: '#CBA6F7' },
    { tag: t.string, color: '#A6E3A1' },
    { tag: t.comment, color: '#6C7086', fontStyle: 'italic' },
    { tag: t.number, color: '#FAB387' },
    { tag: t.function(t.variableName), color: '#89B4FA' },
    { tag: t.variableName, color: '#CDD6F4' },
    { tag: t.operator, color: '#89DCEB' },
    { tag: t.punctuation, color: '#BAC2DE' },
    { tag: t.typeName, color: '#F9E2AF' },
    { tag: t.bracket, color: '#BAC2DE' },
  ],
});

// 自定义主题：Rose Pine（无 @uiw 官方包）
const rosePine = createTheme({
  theme: 'dark',
  settings: {
    background: '#191724',
    foreground: '#E0DEF4',
    caret: '#EBBCBA',
    selection: '#403D5266',
    selectionMatch: '#403D5266',
    gutterBackground: '#191724',
    gutterForeground: '#6E6A86',
    lineHighlight: '#FFFFFF08',
  },
  styles: [
    { tag: t.keyword, color: '#C4A7E7' },
    { tag: t.string, color: '#F6C177' },
    { tag: t.comment, color: '#6E6A86', fontStyle: 'italic' },
    { tag: t.number, color: '#EA9A97' },
    { tag: t.function(t.variableName), color: '#EBBCBA' },
    { tag: t.variableName, color: '#E0DEF4' },
    { tag: t.operator, color: '#C4A7E7' },
    { tag: t.punctuation, color: '#908CAA' },
    { tag: t.typeName, color: '#31748F' },
    { tag: t.bracket, color: '#908CAA' },
  ],
});

// 自定义主题：Kanagawa（无 @uiw 官方包）
const kanagawa = createTheme({
  theme: 'dark',
  settings: {
    background: '#1F1F28',
    foreground: '#DCD7BA',
    caret: '#C8C093',
    selection: '#2D4F6766',
    selectionMatch: '#2D4F6766',
    gutterBackground: '#1F1F28',
    gutterForeground: '#545464',
    lineHighlight: '#FFFFFF08',
  },
  styles: [
    { tag: t.keyword, color: '#C79553' },
    { tag: t.string, color: '#98BB6C' },
    { tag: t.comment, color: '#545464', fontStyle: 'italic' },
    { tag: t.number, color: '#DCAE96' },
    { tag: t.function(t.variableName), color: '#957FB8' },
    { tag: t.variableName, color: '#DCD7BA' },
    { tag: t.operator, color: '#C79553' },
    { tag: t.punctuation, color: '#716E61' },
    { tag: t.typeName, color: '#7E9CD8' },
    { tag: t.bracket, color: '#716E61' },
  ],
});

// 主题配置
export interface ThemeConfig {
  id: string;
  label: string;
  color: string;
  isDark: boolean;
  windowBg: string;
  headerBg: string;
  textColor: string;
  editorTheme: Extension;
}

export const THEMES: ThemeConfig[] = [
  // ---- 暗色主题 ----
  {
    id: 'vscode-dark',
    label: 'VS Code Dark+',
    color: '#1E1E1E',
    isDark: true,
    windowBg: '#1E1E1E',
    headerBg: '#252526',
    textColor: '#D4D4D4',
    editorTheme: uiwThemes.vscodeDark,
  },
  {
    id: 'one-dark',
    label: 'One Dark',
    color: '#282C34',
    isDark: true,
    windowBg: '#282C34',
    headerBg: '#21252B',
    textColor: '#ABB2BF',
    editorTheme: oneDark,
  },
  {
    id: 'dracula',
    label: 'Dracula',
    color: '#282A36',
    isDark: true,
    windowBg: '#282A36',
    headerBg: '#21222C',
    textColor: '#F8F8F2',
    editorTheme: uiwThemes.dracula,
  },
  {
    id: 'github-dark',
    label: 'GitHub Dark',
    color: '#0D1117',
    isDark: true,
    windowBg: '#0D1117',
    headerBg: '#161B22',
    textColor: '#C9D1D9',
    editorTheme: uiwThemes.githubDark,
  },
  {
    id: 'nord',
    label: 'Nord',
    color: '#2E3440',
    isDark: true,
    windowBg: '#2E3440',
    headerBg: '#272C36',
    textColor: '#D8DEE9',
    editorTheme: uiwThemes.nord,
  },
  {
    id: 'solarized-dark',
    label: 'Solarized Dark',
    color: '#002B36',
    isDark: true,
    windowBg: '#002B36',
    headerBg: '#073642',
    textColor: '#839496',
    editorTheme: uiwThemes.solarizedDark,
  },
  {
    id: 'tokyo-night',
    label: 'Tokyo Night',
    color: '#1A1B26',
    isDark: true,
    windowBg: '#1A1B26',
    headerBg: '#16161E',
    textColor: '#A9B1D6',
    editorTheme: uiwThemes.tokyoNight,
  },
  {
    id: 'tokyo-night-storm',
    label: 'Tokyo Night Storm',
    color: '#24283B',
    isDark: true,
    windowBg: '#24283B',
    headerBg: '#1F2335',
    textColor: '#A9BDCC',
    editorTheme: uiwThemes.tokyoNightStorm,
  },
  {
    id: 'catppuccin',
    label: 'Catppuccin Mocha',
    color: '#1E1E2E',
    isDark: true,
    windowBg: '#1E1E2E',
    headerBg: '#181825',
    textColor: '#CDD6F4',
    editorTheme: catppuccinMocha,
  },
  {
    id: 'gruvbox-dark',
    label: 'Gruvbox Dark',
    color: '#282828',
    isDark: true,
    windowBg: '#282828',
    headerBg: '#1D2021',
    textColor: '#EBDBB2',
    editorTheme: uiwThemes.gruvboxDark,
  },
  {
    id: 'rose-pine',
    label: 'Rose Pine',
    color: '#191724',
    isDark: true,
    windowBg: '#191724',
    headerBg: '#1F1D2E',
    textColor: '#E0DEF4',
    editorTheme: rosePine,
  },
  {
    id: 'kanagawa',
    label: 'Kanagawa',
    color: '#1F1F28',
    isDark: true,
    windowBg: '#1F1F28',
    headerBg: '#16161D',
    textColor: '#DCD7BA',
    editorTheme: kanagawa,
  },
  {
    id: 'material-dark',
    label: 'Material Dark',
    color: '#2E3235',
    isDark: true,
    windowBg: '#2E3235',
    headerBg: '#272B2E',
    textColor: '#BDBDBD',
    editorTheme: uiwThemes.materialDark,
  },
  {
    id: 'monokai',
    label: 'Monokai',
    color: '#272822',
    isDark: true,
    windowBg: '#272822',
    headerBg: '#1E1F1C',
    textColor: '#F8F8F2',
    editorTheme: uiwThemes.monokai,
  },
  {
    id: 'atomone',
    label: 'Atom One',
    color: '#272C35',
    isDark: true,
    windowBg: '#272C35',
    headerBg: '#21262E',
    textColor: '#AEB7B8',
    editorTheme: uiwThemes.atomone,
  },
  {
    id: 'abyss',
    label: 'Abyss',
    color: '#000C18',
    isDark: true,
    windowBg: '#000C18',
    headerBg: '#000A14',
    textColor: '#6688CC',
    editorTheme: uiwThemes.abyss,
  },
  {
    id: 'androidstudio',
    label: 'Android Studio',
    color: '#282B2E',
    isDark: true,
    windowBg: '#282B2E',
    headerBg: '#22252A',
    textColor: '#A9B7C6',
    editorTheme: uiwThemes.androidstudio,
  },
  {
    id: 'andromeda',
    label: 'Andromeda',
    color: '#23262E',
    isDark: true,
    windowBg: '#23262E',
    headerBg: '#1C1F27',
    textColor: '#D5CED9',
    editorTheme: uiwThemes.andromeda,
  },
  {
    id: 'aura',
    label: 'Aura',
    color: '#21202E',
    isDark: true,
    windowBg: '#21202E',
    headerBg: '#1A1926',
    textColor: '#EDECEE',
    editorTheme: uiwThemes.aura,
  },
  {
    id: 'bespin',
    label: 'Bespin',
    color: '#28211C',
    isDark: true,
    windowBg: '#28211C',
    headerBg: '#201B17',
    textColor: '#9D9B97',
    editorTheme: uiwThemes.bespin,
  },
  {
    id: 'copilot',
    label: 'Copilot',
    color: '#232A2F',
    isDark: true,
    windowBg: '#232A2F',
    headerBg: '#1C2328',
    textColor: '#939DA5',
    editorTheme: uiwThemes.copilot,
  },
  {
    id: 'darcula',
    label: 'Darcula',
    color: '#2B2B2B',
    isDark: true,
    windowBg: '#2B2B2B',
    headerBg: '#232323',
    textColor: '#F8F8F2',
    editorTheme: uiwThemes.darcula,
  },
  {
    id: 'duotone-dark',
    label: 'Duotone Dark',
    color: '#2A2734',
    isDark: true,
    windowBg: '#2A2734',
    headerBg: '#22202C',
    textColor: '#6C6783',
    editorTheme: uiwThemes.duotoneDark,
  },
  {
    id: 'kimbie',
    label: 'Kimbie Dark',
    color: '#221A0F',
    isDark: true,
    windowBg: '#221A0F',
    headerBg: '#1B150C',
    textColor: '#D3AF86',
    editorTheme: uiwThemes.kimbie,
  },
  {
    id: 'monokai-dimmed',
    label: 'Monokai Dimmed',
    color: '#1E1E1E',
    isDark: true,
    windowBg: '#1E1E1E',
    headerBg: '#181818',
    textColor: '#C5C8C6',
    editorTheme: uiwThemes.monokaiDimmed,
  },
  {
    id: 'okaidia',
    label: 'Okaidia',
    color: '#272822',
    isDark: true,
    windowBg: '#272822',
    headerBg: '#1F201B',
    textColor: '#FFFFFF',
    editorTheme: uiwThemes.okaidia,
  },
  {
    id: 'red',
    label: 'Red',
    color: '#390000',
    isDark: true,
    windowBg: '#390000',
    headerBg: '#2E0000',
    textColor: '#F8F8F8',
    editorTheme: uiwThemes.red,
  },
  {
    id: 'sublime',
    label: 'Sublime',
    color: '#303841',
    isDark: true,
    windowBg: '#303841',
    headerBg: '#282E35',
    textColor: '#FFFFFF',
    editorTheme: uiwThemes.sublime,
  },
  {
    id: 'tomorrow-night-blue',
    label: 'Tomorrow Night Blue',
    color: '#002451',
    isDark: true,
    windowBg: '#002451',
    headerBg: '#001D42',
    textColor: '#FFFFFF',
    editorTheme: uiwThemes.tomorrowNightBlue,
  },
  {
    id: 'white-dark',
    label: 'White Dark',
    color: '#000000',
    isDark: true,
    windowBg: '#000000',
    headerBg: '#0A0A0A',
    textColor: '#FFFFFF',
    editorTheme: uiwThemes.whiteDark,
  },
  {
    id: 'xcode-dark',
    label: 'Xcode Dark',
    color: '#292A30',
    isDark: true,
    windowBg: '#292A30',
    headerBg: '#222328',
    textColor: '#CECFD0',
    editorTheme: uiwThemes.xcodeDark,
  },
  {
    id: 'abcdef',
    label: 'Abcdef',
    color: '#0F0F0F',
    isDark: true,
    windowBg: '#0F0F0F',
    headerBg: '#0A0A0A',
    textColor: '#DEFDEF',
    editorTheme: uiwThemes.abcdef,
  },
  {
    id: 'console-dark',
    label: 'Console Dark',
    color: '#000000',
    isDark: true,
    windowBg: '#000000',
    headerBg: '#0A0A0A',
    textColor: '#FFFFFF',
    editorTheme: uiwThemes.consoleDark,
  },
  {
    id: 'basic-dark',
    label: 'Basic Dark',
    color: '#2E3235',
    isDark: true,
    windowBg: '#2E3235',
    headerBg: '#272B2E',
    textColor: '#DDDDDD',
    editorTheme: uiwThemes.basicDark,
  },
  // ---- 亮色主题 ----
  {
    id: 'vscode-light',
    label: 'VS Code Light',
    color: '#FAFAFA',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#1E1E1E',
    editorTheme: uiwThemes.vscodeLight,
  },
  {
    id: 'github-light',
    label: 'GitHub Light',
    color: '#FAFAFA',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#24292E',
    editorTheme: uiwThemes.githubLight,
  },
  {
    id: 'solarized-light',
    label: 'Solarized Light',
    color: '#FDF6E3',
    isDark: false,
    windowBg: '#FDF6E3',
    headerBg: '#EEE8D5',
    textColor: '#657B83',
    editorTheme: uiwThemes.solarizedLight,
  },
  {
    id: 'tokyo-night-day',
    label: 'Tokyo Night Day',
    color: '#E1E2E7',
    isDark: false,
    windowBg: '#E1E2E7',
    headerBg: '#D5D7DE',
    textColor: '#3760BF',
    editorTheme: uiwThemes.tokyoNightDay,
  },
  {
    id: 'gruvbox-light',
    label: 'Gruvbox Light',
    color: '#FBF1C7',
    isDark: false,
    windowBg: '#FBF1C7',
    headerBg: '#F2E8BC',
    textColor: '#3C3836',
    editorTheme: uiwThemes.gruvboxLight,
  },
  {
    id: 'material-light',
    label: 'Material Light',
    color: '#FAFAFA',
    isDark: false,
    windowBg: '#FAFAFA',
    headerBg: '#F0F0F0',
    textColor: '#90A4AE',
    editorTheme: uiwThemes.materialLight,
  },
  {
    id: 'basic-light',
    label: 'Basic Light',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#2E3440',
    editorTheme: uiwThemes.basicLight,
  },
  {
    id: 'bbedit',
    label: 'BBEdit',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#000000',
    editorTheme: uiwThemes.bbedit,
  },
  {
    id: 'console-light',
    label: 'Console Light',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#000000',
    editorTheme: uiwThemes.consoleLight,
  },
  {
    id: 'duotone-light',
    label: 'Duotone Light',
    color: '#FAF8F5',
    isDark: false,
    windowBg: '#FAF8F5',
    headerBg: '#F0EDEA',
    textColor: '#B29762',
    editorTheme: uiwThemes.duotoneLight,
  },
  {
    id: 'eclipse',
    label: 'Eclipse',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#000000',
    editorTheme: uiwThemes.eclipse,
  },
  {
    id: 'quietlight',
    label: 'Quiet Light',
    color: '#F5F5F5',
    isDark: false,
    windowBg: '#F5F5F5',
    headerBg: '#EBEBEB',
    textColor: '#333333',
    editorTheme: uiwThemes.quietlight,
  },
  {
    id: 'white-light',
    label: 'White Light',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#000000',
    editorTheme: uiwThemes.whiteLight,
  },
  {
    id: 'xcode-light',
    label: 'Xcode Light',
    color: '#FFFFFF',
    isDark: false,
    windowBg: '#FFFFFF',
    headerBg: '#F0F0F0',
    textColor: '#3D3D3D',
    editorTheme: uiwThemes.xcodeLight,
  },
  {
    id: 'noctis-lilac',
    label: 'Noctis Lilac',
    color: '#F2F1F8',
    isDark: false,
    windowBg: '#F2F1F8',
    headerBg: '#EBEAF0',
    textColor: '#0C006B',
    editorTheme: uiwThemes.noctisLilac,
  },
];
